### ISSUE TITLE
Naming Bob's discovery tool

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/hapi-tasks#30]
Bob's tool ([here](https://hapi-server.org/servers/)) for seeing which servers and datasets are available, and which provides example plots and scripts for downloading data has always been unnamed, and we should have a name for it.  Suggested names include:
* HAPI Browser
* HAPI Discovery Tool
* HAPI Explorer
At the 2024-11-18 meeting we quickly settled on HAPI Discovery Tool, but this ticket will make it official and capture any other needed discussion.

**Comment by jvandegriff** [comment]
I thought we had said "HAPI Data Explorer Tool"  - this is what I've been calling it in presentations.

**Comment by jvandegriff** [comment]
HAPI Data Explorer Tool
